=== Rolo27s/XML-documentation/XML_DTD_15-20/e16.dtd
<!ELEMENT listacompras (venta+)>
<!ELEMENT venta (ventaacredito | ventainmediata)>
<!ELEMENT ventaacredito (fechainpago?, cantidad)>
<!ELEMENT ventainmediata (cantidad, divisa)>
<!ELEMENT fechainpago (#PCDATA)>
<!ELEMENT cantidad (#PCDATA)>
<!ELEMENT divisa (#PCDATA)>

=== Rolo27s/XML-documentation/XML_DTD_15-20/e16.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE listacompras SYSTEM "e16.dtd">
<listacompras>
    <venta>
        <ventaacredito>
            <fechainpago>28-04-2023</fechainpago>
            <cantidad>4</cantidad>
        </ventaacredito>
    </venta>
    <venta>
        <ventaacredito>
            <cantidad>18</cantidad>
        </ventaacredito>
    </venta>
    <venta>
        <ventainmediata>
            <cantidad>11</cantidad>
            <divisa>Euros</divisa>
        </ventainmediata>
    </venta>
</listacompras>
